// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_all.Data;

#nullable disable

namespace asp_all.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp_all.Data.Entities.UserAccess", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dk")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserRoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("UserAccesses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0e98ef0-917f-4bf7-90e9-cba9bbd86c04"),
                            CreatedAt = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Dk = "BA8C615C65B7A66750C12605DF7602FDB037A12C",
                            Login = "DefaultAdministrator",
                            Salt = "4009BA69-7EFC-4E4F-A9AF-FEC77B759BC6",
                            UserId = new Guid("41e5ed40-ab13-4b5c-b1d0-3722023ea5c7"),
                            UserRoleId = new Guid("56d473ba-ed6b-4695-aebf-439e2102f2c3")
                        });
                });

            modelBuilder.Entity("asp_all.Data.Entities.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41e5ed40-ab13-4b5c-b1d0-3722023ea5c7"),
                            Birthdate = new DateTime(2026, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@change.me",
                            Name = "Default Administrator"
                        });
                });

            modelBuilder.Entity("asp_all.Data.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CreateLevel")
                        .HasColumnType("int");

                    b.Property<int>("DeleteLevel")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReadLevel")
                        .HasColumnType("int");

                    b.Property<int>("UpdateLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bc84c3aa-f62f-44c6-b822-ae954f450a53"),
                            CreateLevel = 0,
                            DeleteLevel = 0,
                            Description = "Користувачі, що самі зареєструвались на сайті. Мінімальні права доступу",
                            Name = "Self Registered",
                            ReadLevel = 0,
                            UpdateLevel = 0
                        },
                        new
                        {
                            Id = new Guid("56d473ba-ed6b-4695-aebf-439e2102f2c3"),
                            CreateLevel = -1,
                            DeleteLevel = -1,
                            Description = "Користувач з максимальним доступом, через якого вводяться інші ролі та доступи",
                            Name = "Root Administrator",
                            ReadLevel = -1,
                            UpdateLevel = -1
                        });
                });

            modelBuilder.Entity("asp_all.Data.Entities.UserAccess", b =>
                {
                    b.HasOne("asp_all.Data.Entities.UserData", "UserData")
                        .WithMany("UserAccesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("asp_all.Data.Entities.UserRole", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserData");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("asp_all.Data.Entities.UserData", b =>
                {
                    b.Navigation("UserAccesses");
                });
#pragma warning restore 612, 618
        }
    }
}
